[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyqtcompat"
version = "0.1.0a0"
description = "A single-module Qt binding compatibility layer for PyQt6, PySide6, PyQt5, PySide2, PyQt4, and PySide."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name = "Jifeng Wu", email = "jifengwu2k@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "detect-qt-binding"
]

[project.urls]
"Homepage" = "https://github.com/jifengwu2k/pyqtcompat"
"Bug Tracker" = "https://github.com/jifengwu2k/pyqtcompat/issues"
